
services:
  db:
    image: postgres:14-alpine
    container_name: recicla_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: recicla_backend
    restart: always
    environment:
      PORT: ${PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      PGHOST: ${DB_HOST}
      PGUSER: ${DB_USER}
      PGPASSWORD: ${DB_PASSWORD}
      PGDATABASE: ${DB_DATABASE}
      PGPORT: ${DB_PORT}
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
      - ./migrations:/usr/src/app/migrations 
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: recicla_frontend
    restart: always
    ports:
      - '8080:80'
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - backend

volumes:
  pg_data: